using System;
using System.Collections.Generic;
using System.Text;

namespace Party_Bud
{
    class DareQuestionSet
    {
        public string[] Setup()
        {
            var random = new Random();
            random.Shuffle(questions);
            return questions;
        }

        string[] questions = new string[] {
            "Ta av undertøyet (privat) og ha det på hodet resten av spillet.",
            "La gruppen velge en sang og leppesynkronisere til sangen mens de viser et show for alle spillerne.",
            "Kyss en spiller etter eget valg.",
            "Kle deg ut som det motsatte kjønn, og la et bilde bli tatt av deg.",
            "La noen i gruppen gi deg en ny frisyre.",
            "La øynene koble deg sammen og kjenne igjen en medspiller etter lukten.",
            "Få øyenbrynene plukket av en annen spiller.",
            "Ta av alle sokkene og stikk dem i buksene / og / eller bh-en.",
            "Åpne deg selv som en drittsekk og ende opp med en person du ønsker.",
            "Oppfør deg som en hooker eller en hustler og prøv å få noen til å kjøpe deg.",
            "Sminke med mat fra kjøkkenet.",
            "Mat en person etter eget valg med spraykrem.",
            "Overbevis noen om å kjøpe deg som slaver - ved å tilby ham tjenester du må overholde!",
            "Lekk et objekt du ønsker.",
            "Mal drømmejenta / drømmemannen din så sann mot originalen som mulig.",
            "Lag meg en (ekkel / morsom / romantisk) kjærlighetserklæring.",
            "Lag en person til ditt valg fra runden til et ekteskapsforslag.",
            "Bytt med klærne (helst en kvinne med en mann og omvendt).",
            "Kvinne: ta av deg BH-en og ta den til meg.",
            "Mann: ta av deg boksershortsen og gi dem til meg.",
            "hvisk en person etter eget valg ekle ting i øret, og prøv å gjøre det.",
            "Selg kjønnsorganene dine som et produkt fra supermarkedet / elektronikkbutikken / grønnsaksboden / forhandleren.",
            "Sett deg på fanget til en person du velger - eller sett henne på fanget og spill en orgasme.",
            "Velg en lagkamerat for å gi deg et kyss.",
            "Kyss en person av samme kjønn så godt du kan.",
            "Ta en person du velger i buksene.",
            "Streiv etter meg så godt du kan.",
            "Bruk leppene og tennene for å åpne buksene til en medspiller som du velger.",
            "Fortell en stygg historie og bruk så mange skitne ord som mulig.",
            "Demonstrer med en lagkamerat din favoritteksodus og kommenter alt.",
            "Introduser den perfekte blowjoben med en banan eller hage agurk.",
            "Ta en av lagkameratene dine så forførende og erotisk som mulig fra T-skjorten og kyss ham / henne fra navlen til midjen.",
            "Lag et erotisk bilde av en lagkamerat etter eget valg.",
            "Prøv å forføre en person etter eget valg og gå så langt du vil …",
            "Piss fra balkongen.",
            "Organiser en striptease.",
            "Gi en lagkamerat et kyss på bar bunn.",
            "Ta en banan eller agurk og simuler den perfekte BlowJob.",
            "Drikk neste drink på Ex.",
            "Klokke i undertøy kledd på naboen din og beklager støyen.",
            "Savner en medspiller med en hickkey.",
            "Gjennomfør en erotisk samtale med en medspiller som du velger.",
            "Gi et kyss til motstanderen til høyre.",
            "Vis runden din bare mage.",
            "Hold hånden på en person du velger i 5 minutter.",
            "La deg bli stylet av en lagkamerat og en frisyre.",
            "Massér føttene til en spiller etter eget valg.",
            "Lag en magedans i 1 minutt.",
            "Gjør personen til venstre for et romantisk ekteskapsforslag.",
            "Gi et kyss på kinnene til alle tilstedeværende kvinner.",
            "Bytt klærne med den andre spilleren rett overfor.",
            "Gi en lagkamerat en hodemassasje på 2 minutter.",
            "Simulere en ape i en omgang.",
            "Gjør et ansikt først når du blir spurt om noe.",
            "Bare spis noe uten å bruke hendene.",
            "Spill Gollum fra Lord of the Rings i 1 runde.",
            "Mat enhver spiller med en matbit.",
            "Posisjon 1 minutt som en kroppsbygger.",
            "Bestem innen 1 minutt hvor håret som er best.",
            "Dans til sangen, hva som blir spilt.",
            "kyss på kinnet / munnen til en annen seksuell person.",
            "Vis oss magen din.",
            "Hold hendene i 5 minutter.",
            "Bytt T-skjorte med personen høyre / venstre for deg.",
            "slikke gulvet.",
            "Mat personen til høyre ved siden av deg med noe velsmakende.",
            "Drikk et stort glass cola på Eks.",
            "Gjør 5 armhevinger.",
            "La deg bli stylet av lagkameraten som etterlot en åpenbar frisyre.",
            "Fortell personen hvor flott han / hun er.",
            "Nevn en ting om deg som du allerede har mottatt komplimenter for.",
            "Beskriv din verste nåværende lærer.",
            "Spis noe og later som det er det smakeste du noen gang har spist.",
            "Gjør det morsomste grimasen du kan tenke på.",
            "Lag fladelyder.",
            "Ring en venn og si at du er gravid.",
            "Finn ut hvor håret lukter best.",
            "Kyss den andre kjønnsmannen som kommer først til høyre for deg.",
            "Vis armmusklene.",
            "Kast personen et forførende blikk til venstre for deg.",
            "Gi personen som sitter 2 steder til høyre et kyss på kinnet.",
            "Oppfør deg som en kylling i to minutter.",
            "Følg en lærer du ønsker.",
            "Spilleren til høyre for deg kan blande et brygg av alle slags ingredienser, og du må drikke det.",
            "Ta av deg skjorta. Kvinner også BH-en.",
            "Gjør det med partneren din med hånden.",
            "Slikke brystvortene til partneren din.",
            "Blindfold partneren din og skjem bort ham.",
            "Stripe til partneren din. Hvis du allerede er naken, kler du deg igjen og deretter striper deg.",
            "Spilleren til høyre for deg åpner alle knapper og glidelåser.",
            "Ta av deg toppen - kvinner tar også BH-en.",
            "Spe på brystvortene dine og masser dem med det.",
            "Imiter en utstiller.",
            "Bruk neste runde med lek naken.",
            "Drikk neste drink på Ex.",
            "Spill en orgasme.",
            "Gjør en striptease.",
            "Velg en lagkamerat som må ta buksene.",
            "Ta en banan eller agurk og simuler den perfekte BlowJob.",
            "Gi spilleren et kyss til deg over veien.",
            "Ta av deg klærne og forklar fordelene med kjønnsorganene dine for andre spillere.",
            "Masser ditt eget bryst på en erotisk måte.",
            "Fortell en skitten historie.",
            "Ring en fremmed og tilby telefonsex.",
            "Beskriv kjønnsorganene dine som et produkt.",
            "Pinkel fra balkongen.",
            "Sprøyt krem på brystet og la det slikke av en lagkamerat",
            "Send en selfie med et kyss til eksen din.",
            "Ring Burger King og spør hvor neste McDonald’s er.",
            "La deg gjøre opp av personen til høyre. Han / hun blir bind for øynene!",
            "Gå til kjøleskapet. Åpne eventuelle gjenværende pakker og la dem bli halvspist.",
            "Sett armen på toalettet i ti sekunder.",
            "Mal en mono-bryn og legg deretter en selfie på Insta.",
            "Ring moren din og si at du har en baby.",
            "Berør motstandens tunge med tungen i ti sekunder.",
            "Skriv i den første WhatsApp-gruppen du finner: “Jeg er lei av deg!”",
            "Forklar i Instagram-historien hvorfor alle dine følgere irriterer deg.",
            "Drikk et skudd med olivenolje.",
            "Ha en dialog med et element og late som du krangler.",
            "Overrask motstanderen med en runddans.",
            "Gi personen til venstre et kyss på baken.",
            "Vis runden din siste WhatsApp-chat."
        };
    }
}
