using System;
using System.Collections.Generic;
using System.Text;

namespace Party_Bud
{
    class TruthQuestionSet
    {
        public string[] Setup()
        {
            var random = new Random();
            random.Shuffle(questions);
            return questions;
        }

        string[] questions = new string[] {
            "Hva er det første du ville gjort hvis du skulle våkne opp som det motsatte kjønn?",
            "Har du noen gang latt noen andre komme i trøbbel for noe du gjorde?",
            "Hva er det mest pinlige du noen gang har gjort?",
            "Hva er den mest latterlige grunnen til at du noen gang har brutt opp med noen over?",
            "Hva er den groveste vanen du har?",
            "Hva synes du er din beste funksjon? Og hva er det verste?",
            "Hva er det modigste du noen gang har gjort?",
            "Hvem i runden vil du trollbinde på en gris?",
            "Når var sist gang du tisset sengen?",
            "Hva drømmer du om å sove mest?",
            "Hvis du hadde tenkt å tjene pengene dine ulovlig, hvordan ville du da tjent dem?",
            "Hva er noe barnslig som du fortsatt gjør?",
            "Hvis du var blind, hvem i runden ville da være førerhunden din?",
            "Hva kan imponere deg mest?",
            "Hvis du bare hadde lov til å bruke 3 ord resten av kvelden fra nå av - hva ville det være?",
            "Hvis du var en diktator, hvilken lov ville du lovfestet først?",
            "Hvis du hadde levd under nazitiden, hvem ville du ha vært?",
            "Hva var den mest pinlige opplevelsen i skoletiden / studietiden / utdannelsen / i fjor?",
            "Hva var den største feilen i livet ditt?",
            "Hva ville du aldri gjort - selv om du vet at du bare har 12 timer til å leve?",
            "Hvilken krenkelse har du begått?",
            "Fortell en hemmelighet fra barndommen din.",
            "Hva er din største (hemmelige) vise?",
            "Hva vil du gjøre med meg … (eller person xy), hvis du da kan slette minnet (henne, hans …)?",
            "Hva er det verste du noen gang har gjort med noen?",
            "I hvem har du hatt den største knusen på hvem?",
            "Har du noen gang vært forelsket i en av de tilstedeværende?",
            "Hvis du var en vampyr, hvem av oss ville du bitt nå?",
            "Hva er det verste du noen gang har opplevd?",
            "Hva var din verste kurv?",
            "Har du noen gang spratt buksene dine offentlig?",
            "Hva er din mørkeste fantasi?",
            "Hva er det kjekkeste du noen gang har opplevd med en annen person?",
            "Hva er den største Abturner for deg?",
            "Hva liker du mest med kroppen din og hva er den styggeste?",
            "Hvem fra vår runde vil du se naken?",
            "Hvem i omgangen kunne du bli forelsket i mest?",
            "Har du noen gang hatt en erotisk drøm der noen fra denne runden skjedde?",
            "Hvis du ville tatovere deg selv i underlivet - hva ville være der?",
            "Hva er viktigere i et forhold - sex eller kjærlighet?",
            "Synes du sex er kult, bra, greit, noen ganger fint - eller er det ikke så viktig for deg?",
            "Hva er det som gjør deg virkelig god sex?",
            "Hvor mange ganger i uken / måneden har du sex - og hvor ofte vil du ha sex?",
            "Hvor mange forskjellige sexpartnere har du allerede sovet med?",
            "Hvilken del av kroppen tenner deg mest?",
            "Hvordan, hvor og med hvem hadde du din første gang?",
            "Hvor viktig er et utvidet forspill for deg?",
            "Hva må en mann / kvinne gjøre for å forføre deg?",
            "Har du noen gang hatt et trekant? Og hvordan likte du det?",
            "Har du noen gang hatt sex med en god venn?",
            "Har du noen gang hatt sex med en av denne gruppen - bortsett fra partneren din?",
            "Hva er det mest pinlige øyeblikket i sex du noen gang har hatt?",
            "Du er helt forelsket, men da forlater han / hun. Hva må til for å få deg til å stikke av og skrike?",
            "Hva ser du etter hos en kvinne først - bryster, rumpe eller ansikt?",
            "Hva ser du etter hos en mann først, og hva må han ha slik at du tenker: awwwww, kult!",
            "Har du noen gang fornøyd deg med tanken på en av denne runden?",
            "Hva er din favorittposisjon under sex?",
            "Hva skjedde på din vanskeligste dato?",
            "Hva er et absolutt tabu under sex?",
            "Hva er det hotteste du noen gang har gjort?",
            "Har du noen gang hatt cybersex eller telefonsex - og med hvem?",
            "Hva er ditt hemmeste hemmelige ønske?",
            "Hva er bedre - barbert eller ikke-barbert?",
            "Hvem i denne runden synes du at du har den beste sexen?",
            "Hvem vil du gi penger til å sove hos deg?",
            "Hva var din galeste sexopplevelse?",
            "Har du noen gang hatt farlig sex - og hvordan var det egentlig?",
            "Har du noen gang hatt sex med en fremmed? f.eks fra Tinder?",
            "Hvis du gikk på linjen - hva ville være din spesialitet?",
            "Hva liker du mest å tenke på når du tilfredsstiller deg selv?",
            "Har du noen gang hatt sex med samme kjønn?",
            "Du hadde sex med meg. Hva vil du si til meg etterpå?",
            "Hva er den beste måten å legge deg flat på?",
            "Hvem vil du i alle fall sove - enten du er gift eller er forelsket i udødelig?",
            "Hvem hadde du livets beste sex?",
            "Har du noen gang betalt for sex?",
            "Hvem hadde du din siste hete drøm om?",
            "Har du noen gang blitt overrasket under sex - og av hvem?",
            "Hva er din favorittposisjon?",
            "Hvor er din erogene sone?",
            "Støter du på klimaks?",
            "Hvem vil du ha sex med?",
            "Når var sist gang du hadde sex?",
            "Hvor har du intime piercinger?",
            "Hvor mange menn / kvinner har du allerede kysset?",
            "Hva var din verste kurv?",
            "Hvem hadde du den hotteste datoen med?",
            "Hvilken posisjon er favoritten din?",
            "Når var din første gang?",
            "Er du fortsatt jomfru?",
            "På toalettet: Brette eller rulle toalettpapiret?",
            "Hvor barberer du deg overalt?",
            "Har du noen gang vært intim med 2 personer på samme tid?",
            "Har du noen gang hørt søsteren / broren din stønne?",
            "Har du noen gang blitt fanget i onani?",
            "På hvilke steder hadde du sex?",
            "Har du noen gang lurt på noen?",
            "Er du alltid tro?",
            "Hadde du tenåringsknusing?",
            "I hvilken person er du forelsket?",
            "Hvilken kjendis vil du ha en date med?",
            "Hva var det pinlige øyeblikket i livet ditt?",
            "Hvilken munn liker du mest fra gruppen her?",
            "Hvilken spiller har de vakreste hender?",
            "Hvor var ditt første kyss?",
            "Hvem i omgangen vil du aller mest kysse?",
            "Hvem ved bordet er nok den mest kranglete?",
            "Hva var den største feilen i livet ditt?",
            "Har noe flaut skjedd med deg på en date?",
            "Har du noen gang hatt kontakt med narkotika?",
            "Hvilken person vil du kysse nå?",
            "Når var sist du slapp?",
            "Har du noen gang jukset på skoleeksamen?",
            "Har du noen gang stjålet noe tidligere?",
            "Snorker du om natten?",
            "Hvilken er favorittsangen din?",
            "Med hvilken spiller vil du bytte i en uke, og hvorfor?",
            "Du flytter til en ensom øy, hvem fra runden tar du med deg?",
            "Hva er du mest redd for?",
            "Hvor barberer du deg overalt?",
            "Har du et kallenavn?",
            "Ser du inn i toalettskålen før du vasker?",
            "Hvem ga deg den verste hjertesorgen?",
            "Hvor mange ganger har du kysset?",
            "Hva er det mest pinlige som noen gang har skjedd med deg?",
            "Hvor mange typer / jenter har du allerede kysset?",
            "Hvem er du forelsket i?",
            "Hvilken stjerne liker du hot?",
            "Vil du starte noe med XY (sett inn navn)?",
            "Har du noen gang stjålet noe?",
            "Hvilket dyr passer deg best, og hvorfor?",
            "Hva var din verste date?",
            "Hvem vil du kysse nå?",
            "Hva er din hemmelige, mørke fantasi?",
            "Vil du heller tatovere rumpa eller stikke tungen?",
            "Hvilken kjent person vil du overnatte sammen med?",
            "Hvor vil du stråle nå?",
            "Du må gifte deg med en stjerne, hvem?",
            "Hvordan / hvor / med hvem var ditt første kyss?",
            "Er du fortsatt jomfru?",
            "Barberer du deg? Hvis ja, hvor?",
            "Hvilken frisyre har du i kjønnsområdet?",
            "Er du nysgjerrig på å bli intim med en person av ditt eget kjønn?",
            "Elsker du et langt forspill? Hvordan skal det i så fall se ut?",
            "Hva tenker du på når du tilfredsstiller deg selv?",
            "Når var din første gang?",
            "Er du fortsatt jomfru?",
            "Har du noen gang lurt på noen?",
            "Hva var din verste kurv?",
            "Gryter du av orgasme?",
            "Har du noen gang blitt fanget i onani?",
            "Har du noen gang stappet BH-en din?",
            "Når var sist gang du hadde sex?",
            "På hvilke steder har du allerede onanert?",
            "Hva tenker du på når du tilfredsstiller deg selv?",
            "Har du erfaring med tiss?",
            "Har du noen gang hatt sex utendørs?",
            "Hva er din favorittposisjon?",
            "Har du alltid vært trofast?",
            "Hvilken pubisk frisyre har du?",
            "Har du noen gang vært intim med 2 personer på samme tid?",
            "Hva er din hemmelige, mørke fantasi?",
            "Vil du la deg sprute av en mann i ansiktet?",
            "Lekte du legekamper da du var yngre?",
            "Har du allerede hatt homoseksuelle opplevelser?",
            "Har du noen gang hatt telefonsex?",
            "Hvis du måtte gi opp en erotisk kontaktannonse, hva ville det være?",
            "Hvem synes du er flottest i omgangen? Sorter alle mennesker fra søte til stygge.",
            "Hvem i klassen din ville du mest sannsynlig kysse?",
            "Hvem fra denne runden ville du IKKE invitere til neste fest?",
            "Hva var den siste løgnen du fortalte personen til høyre for deg?",
            "Hva var ditt største ønske som du aldri sa?",
            "Hvilken krenkelse har du begått?",
            "Tisser du i dusjen?",
            "Hvilken barnslig oppførsel har du i dag?",
            "Hvor barberer du deg overalt?",
            "Har du noen gang lurt på noen?",
            "Hva er din største frykt som ingen vet om?",
            "I hvem har du noen gang vært forelsket, som ingen vet noe om?",
            "Har du noen gang fylt på BH-ene eller trusen?",
            "Vil du helst være stygg og populær eller pen og upopulær?",
            "Hvilken stilling liker du best?"
        };
    }
}
